# Generated by Django 5.1 on 2024-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
