# Generated by Django 5.1 on 2024-10-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0007_alter_cartitem_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
