# Generated by Django 5.1 on 2024-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0009_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttable',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
