# Generated by Django 5.1 on 2024-10-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0010_restauranttable_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='restauranttable',
            name='is_active',
        ),
    ]
