# Generated by Django 5.1 on 2024-10-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0016_alter_order_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='assigned', max_length=30)),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Menu_Application.order')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Menu_Application.deliverystaff')),
            ],
        ),
    ]
