# Generated by Django 5.1 on 2024-10-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0017_alter_order_order_time_assign'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
