# Generated by Django 5.1 on 2024-10-28 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0020_alter_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('ORDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Menu_Application.order')),
                ('TABLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smart_Menu_Application.restauranttable')),
            ],
        ),
    ]
