# Generated by Django 5.1 on 2024-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smart_Menu_Application', '0021_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ratings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
